### ISSUE TITLE
Design consideration for running multiple networks

### ISSUE THREAD

**Issue by lalithsuresh** [lalithsuresh/odin#2]
Odin's current setup assigns each client a single LVAP, which corresponds to a single-network (from the perspective of the client). Consider support for multiple LVAPs per client.

**Comment by rmerz** [comment]
Are we talking about the infamous guest access ? or the ability to see see multiple networks?

**Comment by lalithsuresh** [comment]
Guest access would follow from the latter.

**Comment by rmerz** [comment]
Ok. so could explain which problem you want to solve?

**Comment by lalithsuresh** [comment]
For guest-access or in general, presenting a client with multiple networks that it may connect to, we need to have multiple LVAPs per client. Each LVAP (or network) can have it's own authentication mechanism as well (for instance, a regular network can be WPA2 Enterprise protected, whereas a guest network would be open).

So in short, we need some refactoring/re-designing at the master.

**Comment by lalithsuresh** [comment]
This had been merged as of commit f86c78880dcd57ee8fde1f33af1b8912cf1b25a4.
